"""Agrego modelo proveedores y su relación con productos 

Revision ID: 486b4d3770b8
Revises: cd7b0048614d
Create Date: 2025-03-10 18:54:01.309607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486b4d3770b8'
down_revision = 'cd7b0048614d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proveedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('contacto', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proveedor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'proveedor', ['proveedor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('proveedor_id')

    op.drop_table('proveedor')
    # ### end Alembic commands ###
