"""Se trabaja en modelo venta con cliente y stck en valores

Revision ID: d6530205d3ef
Revises: e2420075eb69
Create Date: 2025-03-11 23:48:35.000961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6530205d3ef'
down_revision = 'e2420075eb69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('producto_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('cantidad', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('precio_unitario', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('fecha_hora', sa.DateTime(), nullable=False))
        batch_op.create_foreign_key('fk_venta_producto', 'producto', ['producto_id'], ['id'])
        batch_op.drop_column('fecha')
        batch_op.drop_column('total')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('fecha', sa.DATETIME(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fecha_hora')
        batch_op.drop_column('precio_unitario')
        batch_op.drop_column('cantidad')
        batch_op.drop_column('producto_id')

    # ### end Alembic commands ###
